import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:flutter/material.dart';
import 'amplify_outputs.dart'; // auto-generated by: npx ampx sandbox --outputs-format dart --outputs-out-dir lib
import 'features/auth/screens/splash_screen.dart';

Future<void> main() async {
  try {
    WidgetsFlutterBinding.ensureInitialized();
    await _configureAmplify();
    runApp(const BizTrackApp());
  } on AmplifyException catch (e) {
    runApp(Text('Error configuring Amplify: ${e.message}'));
  }
}

Future<void> _configureAmplify() async {
  await Amplify.addPlugin(AmplifyAuthCognito());
  await Amplify.configure(amplifyConfig); // amplifyConfig is exported from amplify_outputs.dart
  safePrint('Amplify configured ✓');
}

class BizTrackApp extends StatelessWidget {
  const BizTrackApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BizTrack',
      home: const SplashScreen(),
    );
  }
}